spring:
  main:
    banner-mode: console
  h2:
    console:
      path: /bookverse_h2
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bookverse_db
    username: sa
  sql:
    init:
      schema-locations: classpath:db/ddl-scripts.sql
      data-locations: classpath:db/dml-scripts.sql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
logging:
  level:
    lt:
      codeacademy:
        bookverse:
          config: DEBUG
          book: INFO
          filter: TRACE
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      # tracking mode will store/show session only in cookie
      tracking-modes: cookie
